# generated by sdd-docs · derived from the code + milestones @ main · 2026-06-12
# Behavior specification (BDD/Gherkin). @milestone-Mx tags map to the ROADMAP.

@milestone-M0
Feature: Workspace foundation
  In order to onboard contributors quickly and make the project publishable
  As a maintainer
  I want correct documentation, licenses, and foundation CI

  Rule: The repository declares MIT OR Apache-2.0 and must contain the texts

    Scenario: License files present
      Given the Cargo.toml declares "MIT OR Apache-2.0"
      When a contributor opens the repository root
      Then a LICENSE-MIT file exists with the full text
      And a LICENSE-APACHE file exists with the full text
      And the README license section links to both

  Rule: A new contributor can build locally

    Scenario: Setup guide covers what is needed
      Given a contributor without the environment configured
      When they read the setup guide (README/CONTRIBUTING)
      Then they find the Rust requirements
      And they find the GTK4/libadwaita system dependencies
      And they find the Makefile commands

  Rule: CI does not run the Rust matrix for changes that do not touch Rust

    Scenario: Site/docs-only PR
      Given a PR that changes only "site/**"
      When CI runs
      Then the site build executes
      And the Rust matrix (fmt, clippy, deny, test, build) is skipped or reported green
      And no required check stays pending

    Scenario: PR that touches Rust code
      Given a PR that changes "crates/**" or a Cargo manifest
      When CI runs
      Then the full Rust validation suite executes

@milestone-M1
Feature: Execute the first request from the UI
  In order to validate the engine end-to-end
  As a user
  I want to send a request and see the response

  Rule: The URL is validated before sending

    Scenario: Invalid URL
      Given the request editor with a malformed URL
      When the user clicks Send
      Then the request is not sent
      And the UI shows a validation error (CoreError::InvalidUrl)

  Rule: A valid request is executed and the response is rendered

    Scenario: Successful GET
      Given a GET method and a reachable valid URL
      When the user clicks Send
      Then the request is executed via HttpExecutor
      And the response_viewer shows status, headers, body, and elapsed time

    Scenario: Network failure
      Given a valid but unreachable URL
      When the user clicks Send
      Then the UI shows an error state derived from HttpError
      And the application does not crash
